# This is a basic workflow to help you get started with Actions

name: CI Test

on:
  push:
    branches: [ script ]
  schedule:
    - cron: '0 22 * * 1-5'
    
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
           
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install python
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt
          
      - name: Execute script
        run: python3 script.py

      - name: Git Commit and Push
        # You may pin to the exact commit or the version.
        # uses: github-actions-x/commit@3638e497fc2bda72d701660f4619cd0efaf0bcf3
        uses: github-actions-x/commit@v2.6
        with:
          # Github Token with commit access
          github-token: ${{ secrets.GH_TOKEN  }}
          # Override branch to push to
          push-branch: script
          # Specify commit message
          commit-message: autocommit
          # Force add files, useful for adding ignored files.
          force-add: true
          # Pull and rebase before commiting. Useful when using commit inside matrix.
          #rebase: # optional, default is false
          # Specific files to add.
          #files: # optional, default is 
          # Committer email. Default is ${name}@users.noreply.github.com
          #email: # optional, default is 
          # Committer name. Default is name of the person or app that initiated the workflow.
          #name: # optional, default is 

      #- name: GitHub Push
        # You may pin to the exact commit or the version.
        # uses: ad-m/github-push-action@40bf560936a8022e68a3c00e7d2abefaf01305a6
        #uses: ad-m/github-push-action@v0.6.0
        #with:
          # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
          #github_token: ${{ secrets.GH_TOKEN  }}
          # Determines if force push is used
          #force: true
          #branch: script

