# This is a basic workflow to help you get started with Actions

name: CI Test

on:
  push:
    branches: [ script ]
  schedule:
    - cron: '0 22 * * 1-5'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
           
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install python
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt
          
      - name: Execute script
        run: python3 script.py
      - name: test1
        run: | 
          cat README.md
          git diff
          git checkout master -m
          git diff
          cat README.md
          git status
      - name: test2
        run: | 
          git commit -m"update readme" --allow-empty
          git status
#git push --force https://${{ secrets.GH_USERNAME }}:${{ secrets.GH_TOKEN }}@github.com/OsiriX-Foundation/DockerEnvironmentVariable.git HEAD:master
