name: Docker env var

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 22 * * 1-5'
    
jobs:
  EnvVar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install Python and dependencies   
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt
          
      - name: Execute script
        run: python3 script.py
      
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.8.0
        with:
          commit_message: github action env var
          commit_options: --allow-empty
          file_pattern: README.md
